name: Android CI

on:
 push:
  branches:
   - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    steps:
    - uses: actions/checkout@v1
    - name: set up Android 29
      uses: actions/setup-android@v1
      with:
        android-version: 29.0.2
    
    - name: Access Permission
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
