name: Android CI

on:
 push:
  branches:
   - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Access Permission
      run: chmod +x ./gradlew
    - name: Creating repository.cfg
      run: touch ~/.android/repositories.cfg
    - name: Build with Gradle
      run: ./gradlew build
